### ISSUE TITLE
HelloWorld make ERROR

### ISSUE THREAD

**Issue by oPiZiL** [orocos-toolchain/typelib#120]
``` 
Makefile:8: This Makefile builds this package with default settings
mkdir -p build
cd build ; cmake .. -DORO_DEFAULT_INSTALL_PREFIX=orocos && make
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Orocos-RTT found in /usr/local/lib/cmake/orocos-rtt/orocos-rtt-gnulinux-libraries.cmake
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- [UseOrocos] Building package HelloWorld without an external buildtool like rosbuild or catkin
-- [UseOrocos] Using Orocos RTT in HelloWorld
-- [UseOrocos] Building component HelloWorld in library HelloWorld-gnulinux
-- [UseOrocos] Building plugin library HelloWorld-plugin
-- [UseOrocos] Building plugin library HelloWorld-service
-- [UseOrocos] Building library HelloWorld-support
-- [UseOrocos] Generating typekit for HelloWorld ...
/usr/lib/ruby/2.3.0/typelib/path.rb:54: warning: circular argument reference - elements
/usr/lib/ruby/2.3.0/orogen/gen/typekit.rb:1330: warning: Insecure world writable dir /home/louw in PATH, mode 040777
/usr/lib/ruby/2.3.0/orogen/gen/typekit.rb:1334:in `block in resolve_toplevel_include_mapping': failed to preprocess /home/louw/rtt_ws/HelloWorld/build/typekit/types/HelloWorld/HelloWorld-types.hpp (ArgumentError)
        from /usr/lib/ruby/2.3.0/tempfile.rb:295:in `open'
        from /usr/lib/ruby/2.3.0/orogen/gen/typekit.rb:1325:in `resolve_toplevel_include_mapping'
        from /usr/lib/ruby/2.3.0/orogen/gen/typekit.rb:1409:in `perform_pending_loads'
        from /usr/lib/ruby/2.3.0/orogen/gen/typekit.rb:1855:in `generate'
        from /usr/local/bin/typegen:116:in `<main>'
CMake Error at /usr/local/lib/cmake/orocos-rtt/UseOROCOS-RTT.cmake:560 (add_subdirectory):
  The source directory

    /home/louw/rtt_ws/HelloWorld/build/typekit

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:34 (orocos_typegen_headers)


-- [UseOrocos] Generating package version 1.0 (default version).
-- [UseOrocos] Exporting targets HelloWorld-typekit.
-- [UseOrocos] Exporting libraries HelloWorld-typekit.
-- [UseOrocos] Exporting include directories /home/louw/rtt_ws/HelloWorld/build/typekit.
-- [UseOrocos] Exporting library directories /usr/local/lib/orocos/gnulinux/HelloWorld/types.
-- Configuring incomplete, errors occurred!
See also "/home/louw/rtt_ws/HelloWorld/build/CMakeFiles/CMakeOutput.log".
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by doudou** [comment]
Hi @oPiZiL. Please report this to the orocos-toolchain developers, for instance at https://github.com/orocos-toolchain/orocos_toolchain

Thanks
