### ISSUE TITLE
Segmentation fault for BASE_LOG_LEVEL=DEBUG

### ISSUE THREAD

**Issue by jakobs** [orocos-toolchain/typelib#36]
I have a script which runs a simulation, which works just fine. However, when I set the BASE_LOG_LEVEL=DEBUG, I get the following segmentation fault (on current master):

Loading scene internal
Orocos[INFO]: applying configuration default on /motors of type simulation::Joints
Typelib[DEBUG]: invalidating all elements in [, ]
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/type.rb:648: [BUG] Segmentation fault
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
...
scripts/run_sim.rb:8:in `<main>'
/home/jakob/dev/wally/base/scripts/lib/rock/bundles.rb:403:in `run'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/transformer/runtime.rb:248:in `start_broadcaster'
/home/jakob/dev/wally/tools/orocos.rb/lib/orocos/process.rb:597:in `run'
/home/jakob/dev/wally/tools/orocos.rb/lib/orocos/process.rb:976:in `guard'
/home/jakob/dev/wally/tools/orocos.rb/lib/orocos/process.rb:598:in `block in run'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/transformer/runtime.rb:250:in `block in start_broadcaster'
/home/jakob/dev/wally/base/scripts/lib/rock/bundles.rb:404:in `block in run'
/home/jakob/dev/wally/tools/orocos.rb/lib/orocos/process.rb:107:in `run'
/home/jakob/dev/wally/tools/orocos.rb/lib/orocos/process.rb:597:in `run'
/home/jakob/dev/wally/tools/orocos.rb/lib/orocos/process.rb:976:in `guard'
/home/jakob/dev/wally/tools/orocos.rb/lib/orocos/process.rb:598:in `block in run'
scripts/run_sim.rb:23:in `block in <main>'
/home/jakob/dev/wally/base/scripts/lib/rock/bundles.rb:443:in `get'
/home/jakob/dev/wally/tools/orocos.rb/lib/orocos/configurations.rb:707:in `apply'
/home/jakob/dev/wally/tools/orocos.rb/lib/orocos/configurations.rb:398:in `apply'
/home/jakob/dev/wally/tools/orocos.rb/lib/orocos/configurations.rb:398:in `each'
/home/jakob/dev/wally/tools/orocos.rb/lib/orocos/configurations.rb:401:in `block in apply'
/home/jakob/dev/wally/tools/orocos.rb/lib/orocos/configurations.rb:451:in `typelib_from_yaml_value'
/home/jakob/dev/wally/tools/orocos.rb/lib/orocos/configurations.rb:427:in `typelib_from_yaml_array'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/container_type.rb:227:in `push'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/container_type.rb:262:in `concat'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/type.rb:277:in `allocating_operation'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/type.rb:304:in `handle_invalidation'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/type.rb:321:in `handle_invalidation_protect_containers'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/container_type.rb:241:in `handle_container_invalidation'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/type.rb:322:in `block in handle_invalidation_protect_containers'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/type.rb:321:in `handle_invalidation_protect_containers'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/container_type.rb:241:in `handle_container_invalidation'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/type.rb:322:in `block in handle_invalidation_protect_containers'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/type.rb:321:in `handle_invalidation_protect_containers'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/container_type.rb:246:in `handle_container_invalidation'
/home/jakob/dev/wally/tools/utilrb/lib/utilrb/logger/forward.rb:14:in `debug'
/usr/lib/ruby/1.9.1/logger.rb:399:in `debug'
/usr/lib/ruby/1.9.1/logger.rb:371:in `add'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/container_type.rb:246:in `block in handle_container_invalidation'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/type.rb:695:in `to_s'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/type.rb:664:in `to_ruby'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib.rb:196:in `to_ruby'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/container_type.rb:207:in `block in extend_for_custom_convertions'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/container_type.rb:157:in `each'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/container_type.rb:157:in `each'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/container_type.rb:158:in `block in each'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/container_type.rb:91:in `get_no_boundary_check'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib.rb:196:in `to_ruby'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/standard_convertions.rb:22:in `block in <module:Typelib>'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/type.rb:648:in `to_byte_array'
/home/jakob/dev/wally/install/lib/ruby/1.9.1/typelib/type.rb:648:in `do_byte_array'

-- C level backtrace information -------------------------------------------
/usr/lib/libruby-1.9.1.so.1.9(+0x155bb9) [0x7f17ec3d9bb9] ../sysdeps/x86_64/multiarch/../strcmp.S:419
/usr/lib/libruby-1.9.1.so.1.9(+0x5966d) [0x7f17ec2dd66d] vfscanf.c:1959
/usr/lib/libruby-1.9.1.so.1.9(rb_bug+0xb3) [0x7f17ec2ddde3] vfscanf.c:834
/usr/lib/libruby-1.9.1.so.1.9(+0xf7436) [0x7f17ec37b436] tsearch.c:601
/lib/x86_64-linux-gnu/libc.so.6(+0x36c30) [0x7f17ebef4c30] ../sysdeps/posix/killpg.c:37
/lib/x86_64-linux-gnu/libc.so.6(+0x98a7e) [0x7f17ebf56a7e] ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:35
/home/jakob/dev/wally/install/lib/libtypeLib.so.1(_ZN18VectorOutputStream5writeEPKhm+0x50) [0x7f17e7c74190] vfprintf.c:2046
/home/jakob/dev/wally/install/lib/typelib/libtypeLang_cSupport.so(_ZNK6String4dumpEPKvmRN7Typelib12OutputStreamEN9__gnu_cxx17__normal_iteratorIPKmSt6vectorImSaImEEEESC_+0xf) [0x7f17e7a1861f]
/home/jakob/dev/wally/install/lib/libtypeLib.so.1(_ZN7Typelib8ValueOps4dumpEPKhmRNS_12OutputStreamEN9__gnu_cxx17__normal_iteratorIPKmSt6vectorImSaImEEEESC_+0x171) [0x7f17e7c70f11] vfprintf.c:1392
/home/jakob/dev/wally/install/lib/libtypeLib.so.1(_ZN7Typelib4dumpEPKhRNS_12OutputStreamERKSt6vectorImSaImEE+0x1a) [0x7f17e7c7148a] vfprintf.c:1660
/home/jakob/dev/wally/install/lib/libtypeLib.so.1(_ZN7Typelib4dumpENS_5ValueERSt6vectorIhSaIhEERKS1_ImSaImEE+0x20) [0x7f17e7c71610] vfprintf.c:1660
/home/jakob/dev/wally/install/lib/ruby/1.9.1/x86_64-linux/typelib_ruby.so(+0xfa5f) [0x7f17e7e9aa5f] /home/jakob/dev/wally/tools/typelib/bindings/ruby/ext/value.cc:540
/usr/lib/libruby-1.9.1.so.1.9(+0x14c1d3) [0x7f17ec3d01d3] ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:791
/usr/lib/libruby-1.9.1.so.1.9(+0x146a95) [0x7f17ec3caa95] ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:764
/usr/lib/libruby-1.9.1.so.1.9(+0x149d8e) [0x7f17ec3cdd8e] ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:1355
/usr/lib/libruby-1.9.1.so.1.9(+0x14b14c) [0x7f17ec3cf14c] ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:2747
/usr/lib/libruby-1.9.1.so.1.9(+0x14b7a1) [0x7f17ec3cf7a1] ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:225
/usr/lib/libruby-1.9.1.so.1.9(+0x14c2d4) [0x7f17ec3d02d4] ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:840
/usr/lib/libruby-1.9.1.so.1.9(+0x146a95) [0x7f17ec3caa95] ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:764
/usr/lib/libruby-1.9.1.so.1.9(+0x149d8e) [0x7f17ec3cdd8e] ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:1355
/usr/lib/libruby-1.9.1.so.1.9(rb_yield+0x240) [0x7f17ec3d5230] ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:492
/usr/lib/libruby-1.9.1.so.1.9(+0xc89be) [0x7f17ec34c9be] fnmatch_loop.c:985
/usr/lib/libruby-1.9.1.so.1.9(+0x14c1d3) [0x7f17ec3d01d3] ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:791
/usr/lib/libruby-1.9.1.so.1.9(+0x146a95) [0x7f17ec3caa95] ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:764
/usr/lib/libruby-1.9.1.so.1.9(+0x149d8e) [0x7f17ec3cdd8e] ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:1355
/usr/lib/libruby-1.9.1.so.1.9(+0x14b14c) [0x7f17ec3cf14c] ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:2747
/usr/lib/libruby-1.9.1.so.1.9(+0x14b7a1) [0x7f17ec3cf7a1] ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:225
/usr/lib/libruby-1.9.1.so.1.9(+0x14c2d4) [0x7f17ec3d02d4] ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:840
/usr/lib/libruby-1.9.1.so.1.9(+0x146a95) [0x7f17ec3caa95] ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:764
/usr/lib/libruby-1.9.1.so.1.9(+0x149d8e) [0x7f17ec3cdd8e] ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:1355
/usr/lib/libruby-1.9.1.so.1.9(+0x14a181) [0x7f17ec3ce181] ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:1614
/usr/lib/libruby-1.9.1.so.1.9(rb_funcall+0xc8) [0x7f17ec3cec88] ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:2415
/usr/lib/libruby-1.9.1.so.1.9(rb_obj_as_string+0x2e) [0x7f17ec38bc4e] argp-parse.c:541
/usr/lib/libruby-1.9.1.so.1.9(+0x1455dd) [0x7f17ec3c95dd] ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:2181
/usr/lib/libruby-1.9.1.so.1.9(+0x149d8e) [0x7f17ec3cdd8e] ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:1355
/usr/lib/libruby-1.9.1.so.1.9(rb_yield+0x240) [0x7f17ec3d5230] ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:492
/usr/lib/libruby-1.9.1.so.1.9(+0x71847) [0x7f17ec2f5847] iofwide.c:316
/usr/lib/libruby-1.9.1.so.1.9(+0x707d2) [0x7f17ec2f47d2] iopopen.c:301
/usr/lib/libruby-1.9.1.so.1.9(st_foreach+0xbc) [0x7f17ec383ecc] ../nss/getXXent_r.c:144
/usr/lib/libruby-1.9.1.so.1.9(+0x715aa) [0x7f17ec2f55aa] libioP.h:905
/usr/lib/libruby-1.9.1.so.1.9(rb_ensure+0xb6) [0x7f17ec2e20a6] putw.c:25
/usr/lib/libruby-1.9.1.so.1.9(rb_hash_foreach+0x36) [0x7f17ec2f66e6] getchar.c:36
/usr/lib/libruby-1.9.1.so.1.9(+0x728ae) [0x7f17ec2f68ae] memstream.c:136
/usr/lib/libruby-1.9.1.so.1.9(+0x14c1d3) [0x7f17ec3d01d3] ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:791
/usr/lib/libruby-1.9.1.so.1.9(+0x146a95) [0x7f17ec3caa95] ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:764
/usr/lib/libruby-1.9.1.so.1.9(+0x149d8e) [0x7f17ec3cdd8e] ../sysdeps/x86_64/multiarch/memcpy-ssse3.S:1355
/usr/lib/libruby-1.9.1.so.1.9(rb_iseq_eval_main+0x9f) [0x7f17ec3d685f] ../sysdeps/x86_64/multiarch/memcpy-ssse3-back.S:1766
/usr/lib/libruby-1.9.1.so.1.9(+0x5ca1a) [0x7f17ec2e0a1a] vfscanf.c:1930
/usr/lib/libruby-1.9.1.so.1.9(ruby_exec_node+0x1d) [0x7f17ec2e185d] perror.c:82
/usr/lib/libruby-1.9.1.so.1.9(ruby_run_node+0x1e) [0x7f17ec2e330e] vfprintf.c:1340
/usr/bin/ruby1.9.1() [0x40086b]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7f17ebedfec5] libc-start.c:287
/usr/bin/ruby1.9.1() [0x400899]

**Comment by jakobs** [comment]
Fixed by #37
